services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web
    depends_on:
      - web-db

  web-db:
    image: postgres:12-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web
